### ISSUE TITLE
Aspect ratio detection seems a bit confused

### ISSUE THREAD

**Issue by caiomatrix** [xternal7/ultrawidify#12]
I was watching [this ](https://www.youtube.com/watch?v=NaTGwlfRB_c) Youtube video and I noticed a very fast and very noticeable change in aspect ratio during playback. Auto-detection seems to be having trouble figuring out the correct aspect ratio and the result is some zooming-in/zooming-out during some shots, for instance at 3:41 through 3:43 and 4:05 through 4:11. Forcing 21:9 did nothing but keeping the video 16:9 with black bars around it. 

Then I went to watch [this](https://www.youtube.com/watch?v=L_u97PqWX6g) music video, which is kind of a test for auto-detection because there's at least four different aspect ratios throughout the video. At the start of it, auto-detection did nothing. It was a case of 21:9 (actually longer but I don't know the exact number) pillarboxed and letterboxed. But as soon as the aspect ratio starts to change (0:34), the auto-detection changes the AR correctly for the rest of the video. The experience was actually great, it was the first time I saw this music video correctly in 21:9. And funny thing was, as I went back to the start of the video, it was correctly set to 21:9. It was like the changes in AR jump started the auto-detection at that point.
 

I'm using FF 56, a 1080p UW monitor and v2 of ultrawidify.

**Comment by xternal7** [comment]
Oh boy, dark videos.

And you're right with the first video. It's not a catastrophic failure and changes in aspect ratio aren't too big, but they're noticeable enough to be annoying. Good news is that since the changes between aspect ratios are minimal, this problem can be fixed easily by preventing aspect ratio changes that are minimal. I suppose I could fix this problem soon.

>Forcing 21:9 did nothing but keeping the video 16:9 with black bars around it.

**How did you force 21:9? Via extension popup in the tab bar or via keyboard shortcuts?**

Note that I might have accidentally swapped default keybinds for 16:9 and 21:9 around when rewriting code to something a bit more sane and easier to maintain. Sorry for that.

RE: second video

>At the start of it, auto-detection did nothing. It was a case of 21:9 

The video at the start is too dark, so extension probably registers it either as a dark frame or "not enough data to determine aspect ratio."

>And funny thing was, as I went back to the start of the video, it was correctly set to 21:9. It was like the changes in AR jump started the auto-detection at that point.

That actually happened because extension doesn't reset video zoom when the video ends. When you skip back to the beginning of the video, extension will retain the last detected aspect ratio by default. Of course, the aspect ratio continues and the script reaches the same conclusion that it reached the first time: "Black bar at the top is of different size than the black bar at the bottom. Something's not right. Let's not do nothing. Can't fuck up if you do nothing."

**Comment by caiomatrix** [comment]
> How did you force 21:9? Via extension popup in the tab bar or via keyboard shortcuts?

**Comment by caiomatrix** [comment]
> Oh boy, dark videos.

So it is because of dark frames? I started to noticed with shot changing from dark to bright, so I guess it was something along those lines.

> How did you force 21:9? Via extension popup in the tab bar or via keyboard shortcuts?

I used the popup in the tab bar. I never used the shortcuts before so I didn't know what to press. lol

I don't know anything about coding, so your reply is pretty interesting from a noob perspective. So far the new detection is working automagically fine, except these few videos. So keep up the good work! :D

**Comment by xternal7** [comment]
>I used the popup in the tab bar. 

Sometimes you may have to click twice. When I was testing, the issue with buttons not working properly happened comparatively rarely though — more often I've had an issue with popup displaying 'no video on this page' error because Firefox ate some initial messages that are being passed between popup and the part of the extension that does all the work.

Second — I've looked up the issue with the first video. Turns out that difference between aspect ratios aren't as small as I expected. Extension now refuses to change aspect ratio if the change is too small, which does seem to help a little, but random switching still happens at times. I guess I'll leave as it is for the time being.

Keyboard shortcuts:

`w` - fits width
`e` - fits height 
`r` - resets video to original size — **broken at the moment**
`a` - automatically detect aspect ratio
`s` - force 16:9
`d` - force 21:9
`x` - force 2:1 (18:9)

(With obvious exception of `a`,) all of the keys disable automatic aspect ratio detection until page is reloaded (or automatic aspect ratio detection is manually re-enabled).

**Comment by xternal7** [comment]
I also think I have the "popup button doesn't work the first time I press it" issue fixed.

I'm not entirely sure, because the issue didn't make any sense to begin with, but I've added a few extra safety thingies that check whether changes the extension does to the page actually get applied in this one relevant case. It seems that if I apply changes too quickly when entering fullscreen after setting the aspect ratio via the popup, the changes get wiped by youtube.

Reset button also no longer broken. 

I'm closing this for the time being. It will probably take a few days before update makes it through AMO, feel free to open a new issue/reopen this one.

Thanks for the reports.
