### ISSUE TITLE
Permission to access data on all websites?

### ISSUE THREAD

**Issue by RoseTheFlower** [xternal7/ultrawidify#13]
The latest version asks for these permissions. It's not necessary to go beyond netflix, youtube and whichever other websites the extension works on. Thankfully, the latest version of Firefox allows me to just stick with the previous version of the extension, so I will do it while I'm looking for safer alternatives.

**Comment by xternal7** [comment]
That is correct. It requires permission for all sites. It doesn't collect anything though. Promise. You can look at the code, it's for all to see.

> so I will do it while I'm looking for safer alternatives.

Be my guest. I'm the only option for Firefox, though, so you'll have to move to Chrome (or a browser that can use Chrome extensions). But first, let me explain why `<all_urls>` permission — there's about two reasons for that:

* The scope of this extension increased. Extension was also rewritten from scratch, and one of the goals of the rewrite was to have extension work on _every_ site that might have videos on them. Even on the sites that I'm not aware of yet.
* [I've seen someone say that a function I use for automatic aspect ratio detection requires `<all_urls>` permission](https://discourse.mozilla.org/t/drawwindow-in-webextension/13811/4) and I didn't care to find out how true that is.

The detailed explanation is as follows:
----

# Reason 1

> It's not necessary to go beyond netflix, youtube and whichever other websites the extension works on.

Originally, this extension worked only on Youtube and Netflix (though Netflix broke some time after September 2017). Of course, when I tried to ~~karmawhore~~ _advertise_ a bit on [/r/ultrawidemasterrace](https://www.reddit.com/r/ultrawidemasterrace) about a year ago, questions started popping up. "Hey can you support site A?" "Can you support site B?" If my memory serves me right, I even got some requests on AMO ("hey can you support site C?"), and of course there's the "hey can you support pornhub plox" ticket that's still opened.

**Long story short, I rewrote extension so it works on every site that has a `<video>` tag** (but in full screen only). It doesn't always work (vid.me, for example, was problematic), but the goal was to have it working on every HTML5 video site before someone asks me to implement support for that site.

**This reason is now obsolete** — or better yet, it's an older version of this reason. Prior to the rewrite, the way I intended to deal with request for support was to crowd-source it to [/r/ultrawidemasterrace](https://www.reddit.com/r/ultrawidemasterrace) because let's face it: half of video streaming sites are US-only, those which aren't are usually region locked. I also haven't made enough in donations to cover subscription costs so ... yeah, crowdsourcing sounded nice.

To make things easier, I was trying to add a settings page where a person could name the website they wanted to have support for and write a quick config file for it — see [v1 branch](https://github.com/xternal7/ultrawidify/tree/v1) for code. But in order for extension for extension to work on user-defined sites, I needed `<all_urls>` permission (as there's no way to add permissions for extra sites later. I could be wrong here though). 

# Reason 2

Aspect ratio autodetection (auto-ar). Now, _Reason #1_ is enough to warrant `<all_urls>` permission by itself, but there's extra stuff.

Auto-ar works like this:

1. find the first <video> element on the page
2. create `<canvas>`
3. draw whatever `<video>` is currently displaying onto canvas
4. read columns of pixels from `<canvas>`, determine where black bars end and video begins
5. change aspect ratio appropriately

Step 3 normally draws an image to a canvas that's displayed off-screen directly from the <video> tag. It works on youtube alright.

It doesn't work on Netflix. Netflix runs DRM, and when you say "hey can you please draw the current frame in this `<video>` tag to this conveniently placed `<canvas>` for me" the browser is like: "u fokin wot m90, this video tag is emptier than your donation box. I can't draw on that canvas because there's nothing for me to draw."

Firefox has this convenient screenshot tool, which you can use to screenshot each specific element. This gave me an idea: what if I try to screenshot the page? After all, Firefox' screenshot tool screenshots the `<video>` tag just fine.

Unfortunately though, you can't invoke that from extension. There's [`getScreenshot()` function](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/getScreenshot), but it only works with iframes. `<video>` aint an iframe. After a while I also found [`context.drawWindow()`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawWindow), which allows me to draw contents of a window onto a `<canvas>` element. This way is inferior to how auto-ar normally works and gives worse/less accurate results, but results nonetheless.

Given how slightly worse auto aspect ratio detection is better than no aspect ratio detection, I decided to implement it with `context.drawWindow()`. Problem: [this method requires `<all_urls>` permission according to this one guy](https://discourse.mozilla.org/t/drawwindow-in-webextension/13811). Since I was in a hurry, I decided to believe him without further investigation.
