### ISSUE TITLE
[Feature Request] Microsoft Edge support

### ISSUE THREAD

**Issue by LexPrima** [xternal7/ultrawidify#14]
This would be very interesting since Edge is the only browser that's provided >1080p and HDR by Netflix.

**Comment by xternal7** [comment]
After I get chrome port working, assuming I can just throw Chrome version at edge with no issues.

**Comment by LexPrima** [comment]
Any updates on this?

**Comment by xternal7** [comment]
Not yet, I keep getting sidetracked by things. (Also: it turns out that you can't kinda just throw the Chrome version at Edge, as Edge is a mix of Firefox and Chrome APIs).

January, february, march were mostly spent fixing the shitshow with performance.
April was stuff getting in the way.
May was mostly spending rewriting this extension so it's not pure spaghetti/cancer to maintain. There's been a few things that bothered me and a few that actually caused issues. (Also added stretch mode while I was at it, has some extras that alternatives don't seem to). 
June, july: sorting out last few issues (popup, saving/loading settings, rewrite of code for communication between popup, background script and content script)

On that note, with the biggest few issues fixed and the rewrite leaving me in a good position for Edge port, I suppose I can finally start with it. Thanks for the reminder.

**Comment by xternal7** [comment]
Update.

Okay this hiatus took longer than expected. Edge kinda seems to work according to some quick tests (nothing too thorough) — if you're curious, you can give it a quick spin. Check out the edge branch and install it as temporary addon.

I decided to hold off pushing the extension to Edge store thingy because #40 popped up. I kinda hoped I'll manage to fix the problem quickly, but life had other plans. In addition to that, I've also been reminded that someone posted a surprisingly useful review over at the place I check the least often (Chrome web store) about a month ago, #43. There's no ETA on either of these two.


If you only ever use Edge for Netflix, there's a few options. Since autodetection _very_ likely won't work on Netflix in Edge anyway, #43 becomes fairly minor annoyance on Netflix. This means I can:

* make this extension netflix-only for Edge while I work on #40 and #43

As a side bonus, 'netflix only' means #40 also can't piss too many people off either. Tell me if that works for you.

**Comment by LexPrima** [comment]
Alright finally had the time to check this out. It doesn't work for me. Neither hotkeys nor settings. Am I on the right branch? It says "Updated 29 days ago"

**Comment by xternal7** [comment]
Yeah, that should be the one. Bit of a bummer it didn't work for you, I guess I have some extra work ahead then.

**Comment by xternal7** [comment]
@LexPrima 

Okay so here's the status update.

* I got extension to sorta-work on Edge. Check out **edge** branch (NOT master). 
* How okay would you be with having to manually enable extension every time you start Edge?

Because here's the thing, I'm not publishing my extension on Microsoft store, and here's why:

**Micro$oft wants €14 for the privilege.** Not only is this number about €14 more than what Mozilla wants for the privilege of accessing AMO and about three times higher than what Google wants for the privilege of accessing Chrome Web Store, the user count on Edge would be probably like 3% of user count of either (and that's a very generous estimate). 

What triggers me here the most isn't the fact that I'd need to pay money. I footed the bill for Chrome Web Store and I footed the bill for Netflix (and got some money in donations to cover that). The part that's pissing me off is that I'd need to pay money for a browser that is, in every way, shape and form, complete and utter trash. First of all I have to deal with outright broken APIs (e.g. `browser.storage.local.set()/.get()` don't work properly at all, especially not in the extension popup), debug tools that are [outright broken](https://i.redd.it/s0bgvdodhno11.png) (notice how I'm filtering for 'FAILED', a string which can be found in grand total of about three lines) and I can make Edge crash in 10 seconds flat -- and then they want me to pay for their shitty product?

At this point it's not even about the money, it's about the principle. I'm not paying money to access what's ultimately a broken product. 

Honestly Microsoft can go fuck themselves.
![I know this middle finger in particular was aimed at noVideo, but that doesn't mean it's not relevant here.](https://user-images.githubusercontent.com/12505802/46114047-73891980-c1e0-11e8-9930-30eeeb56bc2b.png)


# Downsides of not having extension loaded up 

I'll reiterate stuff, but with screenshots:

You'll get this popup after starting Edge. **You will also have to reload the page (or navigate to somewhere else) in order for extension to start.**
![slika](https://user-images.githubusercontent.com/12505802/46114175-05912200-c1e1-11e8-91c7-2217f5bf79e3.png)

The `browser.storage.local.get()/set()` not working properly bit means that 'Extension settings' and 'Settings for this site' tabs don't work properly (extension doesn't remember settings). This is why I've outright disabled them for Edge:

![Feast on dem popup](https://user-images.githubusercontent.com/12505802/46113923-d1693180-c1df-11e8-82f0-ad64cbc57558.png)






And let me say 'fuck Microsoft and fuck Edge' if I haven't done that already.

**Comment by xternal7** [comment]
Actually [here's a handy .zip](https://github.com/xternal7/ultrawidify/blob/master/releases/edge/ultrawidify_edge_v3.2.2.zip) so you don't have to bother with cloning the correct branch.

Sorry for the rant, but I had to vent about the cancer that is Edge.

If you can deal with the popup always asking you to re-enable extensions, fine, download the zip and install the extension manually. I've tested it on youtube and netflix, things that work:

* keyboard shortcuts
* automatic detection only works on youtube
* all options in 'video settings tab' _except_ setting custom aspect ratio and resetting zoom (use 'reset' button in 'cropping mode' instead). 
* you can't convince this extension to work outside of youtube and netflix on edge

If any of these things that I listed above as 'working' don't work, feel free to open a new bug report and I'll try to fix them.
