### ISSUE TITLE
[Bug] Caption text always showed

### ISSUE THREAD

**Issue by heubergen** [xternal7/ultrawidify#2]
Steps to reproduce:

1. Open a yt video in fullscreen (e.g. https://www.youtube.com/watch?v=mEy0JsEnp20)
2. Press 'w' on you keyboard

Expected result:
The video will fit the ultrawide format

Actual result:
There's always this text: _Captions look like this_ which disturb me

**Comment by xternal7** [comment]
Firstly, thanks for the contribution.

Not a bug really, that's a brand new keyboard shortcut conflict. Seems to be a feature youtube recently added to their player, it started to appear somewhere in December 2016, if I recall correctly.

I haven't changed the keybinds because that would suck for people who learned that 'w' is for 'fit to width' _before_ youtube introduced that feature.

# Workarounds

The alternative keybind is `d` (forces 21:9).

You can also change the keybind from 'w' to anything else (and by anything else I mean keys A-Z, with or without modifier keys). At least that's the theory, it should work but it wasn't thoroughly tested yet. (Shame on me, I know)

**Oh and the bottom four entries on the settings page are bugged. I've just noticed that now, but neither of those four options is actually "fit to width".**

# Fixed when?

Not entirely sure if that's an issue that can be reliably "fixed". I'll look into it and see if an extension can block keypresses before they reach the youtube players.

**Comment by xternal7** [comment]
Extension does seem to get keypress events sooner than youtube's player. Depending on how some other things go, the updated version will probably hit AMO somewhere by the end of the week.
