### ISSUE TITLE
2.1.0 not working [Chrome]

### ISSUE THREAD

**Issue by LexPrima** [xternal7/ultrawidify#21]
"No videos were detected on this page. The buttons may not work at all. Check that this site is not blacklisted and reload the page."

Tested on Netflix and Youtube. Reloading or restarting the browser won't fix this. Firefox working though.

**Comment by xternal7** [comment]
Oh boy, please _not_ `tabs.sendMessage` bullshit again. And I thought I've had it solved for like the seventh time.

Anyway: **Do buttons work when you press them?**

Sometimes, this message can come up in error (and it happens more often in Chrome than it does in Firefox, for some reason). I can reproduce the "No videos were detected on this page" bit (no idea how it slipped through testing though), but buttons still work for me.

If they don't work for you ... I'll have a bit bigger problem on my hand.



Extra followup if the popup buttons don't work: **do keyboard shortcuts work?** 

--- **Technical stuff** ... for those who are interested ---

If you're having the issue I've outlined above, here's a reason why. Popup doesn't know whether there's any videos on the page. It must ask the page (content script)¹ whether there's any videos on the page, and it does so. Page script gets the message and responds to it. In some cases, Chrome will lose the response for bullshit reasons (Firefox might do that too, but less often). Because only the response is lost (but not the original message), buttons work just fine even if there's a message telling you no videos were detected on the page.

On the other hand, if not even buttons work, I could have fucked up and built the release version with firefox manifest ... :/ 

__________________

¹it's actually more complicated. ELIdeveloper version: when you switch tabs, background script (not interacting with webpage) asks content script (runs in current tab and can interact with webpage) if there's any videos on the page (tab and any extra frames that are in it. Each frame has its own instance of content script). Content script gives answer, background script saves it. When you open the popup, popup script asks background script whether there's any videos on the page. Background script returns the response.

**Comment by LexPrima** [comment]
No, neither are working. So hopefully only wrong manifest? :D

**Comment by xternal7** [comment]
Okay so I've repacked the extension and pushed it to the chrome store (with a slight version bump — 2.1.1 — for a bugfix that wasn't 100% fixed). It should be available on chrome store in an hour or so. 

**What should work:**
* buttons in popup. If you click a button, aspect ratio should change.
* autodetection (on the first video at least)
* keyboard shortcuts

**What doesn't work:**
* the "no videos detected" warning should still appear. 

If the upper three items don't work, I'll ask you for your OS, Chrome version and other extensions.

**Comment by LexPrima** [comment]
None of these work.

Windows 10 Pro x64
Chrome 64.0.3282.140 (Offizieller Build) (64-Bit)
all other extensions disabled

**Comment by xternal7** [comment]
Okay so I booted up Windows and ... it worked on Youtube just fine?

Try removing and then reinstalling the extension from the web store. If this is somehow caused by settings getting corrupted somehow, this should fix some of the issues.

If reinstalling the extension doesn't work, I'd need to see some logs. If you can spare the time,

1. download this repository (git clone or download as a zip & extract).
2. Go to Chrome extension page, enable developer mode
3. Disable ultrawidify you installed from store
4. Click "install unpacked extension" (or something along the lines)
5. select folder where you extracted this extension to.

Then, navigate to some youtube video. Press F12  to bring up console. Refresh page once the console is opened and wait for it to finish loading.

Console window should look something like this:

![pic.png](https://i.imgur.com/zds80ls.png)

**Comment by LexPrima** [comment]
reinstalling fixed it. Netflix any Youtube working again. Thx
