### ISSUE TITLE
Conflict on Reddit/RES and Gifs

### ISSUE THREAD

**Issue by ryanbr** [xternal7/ultrawidify#22]
Install both extensions, Reedit Enhancement Suite and Ultrawidify under Firefox Nightly (disabled all extensions except these 2)

Visit: https://www.reddit.com/r/Celebs/  watch the occasional gifycat video not load/gets interrupted.

(NSFW) Sample Video; https://youtu.be/kQDrZO5y3-I

Seems to only work if RES is disable or Ultrawidify is disabled.

**Comment by xternal7** [comment]
Noted. Will look into it.

Until then, (if the extension already got updated for you) you can disable extension just for reddit (does not apply to sites in their own frames, e.g. youtube inline player) (click extension button -> settings for this site -> tick 'never/blacklist'). It should work in theory, but that feature hasn't gotten too much testing so I'd appreciate the feedback.

**Comment by xternal7** [comment]
Reddit now comes blacklisted by default.

**Comment by zanch** [comment]
Hello,
I'm having this issue as well, 2 years later.  Was a setting reverted?  I was in the process of making a new bug report and noticed this post, so I've copied my report here:

**Describe the bug**
I noticed that expandos do not work for imgur and probably others.  Funny thing is if you drag an image with ultrawidify enabled it does nothing but if you disable it and go back to reddit without even refreshing, the expando works and will show the gif/image as resized based on what you dragged.  I tried disabling for reddit.com through the settings and could not get expandos to work.  Only disabling from about:addons works.

**To Reproduce**
Enable both RES and Ultrawidify and expand any link with a gif - it does not resize.

**Expected behavior**
Gif should resize when you click and drag.

**Screenshots**
Not really needed.

**Browser and OS**
Firefox v74 (64 Bit)
Windows 10 (latest version in Slow ring)
Ultrawidify v4.4.7

**Additional info**
Would be great if both work.  The trouble with UW screens is that the community has to provide fixes way sooner than companies usually do.  So I do appreciate all the work that has been put into this extension.  I usually like to look into the code to troubleshoot/provide a fix but have not made a Firefox extension before, so I'll leave it to the pros.

Thank you!

**Comment by tamius-han** [comment]
> Was a setting reverted?

Yes, because for a brief period, the extension worked with v.reddit videos — and because popup gets annoying when watching embedded youtube videos on reddit in that case.

Then some day, shit stopped working with v.reddit videos to the point the page was completely broken. In attempt to fix it, I added some CSS that forces the video width and video height at 100%. This seems to have solved the issue. And of course, it's this thing that's causing this issue.

You want to go to 'advanced settings' and delete this thing I've just highlighed:
![image](https://user-images.githubusercontent.com/12505802/77855164-fa142200-71ee-11ea-8ebf-75acc3064a07.png)
Then click out of the box and _then_ close the popup and reload the page.

v.reddit videos no longer seem to be broken as they used to be with this removed — at least on old.reddit (didn't test on redesign), so this should be fine.

It's gonna take a while before update gets pushed because Firefox is causing some issues by refusing to load the extension when I'm testing it.
