### ISSUE TITLE
Youtube pausing video takes some seconds

### ISSUE THREAD

**Issue by TangoFox4** [xternal7/ultrawidify#25]
I just noticed that when I click somewhere on the video, it pauses after some seconds. If I disable the plugin it pauses immediatlely how it is supposed to.

It's kinda random ranging from 1-4 seconds.
The video-settings are affected too, sometimes they don't open at all.

Clicking the Pause-Button works fine.

**Comment by xternal7** [comment]
Ugh. I can't reproduce. I've had this issue randomly pop up in the past, but only while actually doing work on the extension. Not on AMO version, though, and as I said - can't reproduce right now. If you don't mind providing me with some extra info:

1. Does this issue still happen if you manually change aspect ratio (reset/key R should disable automatic aspect ratio detection as well?)
1. b) if the issue stopped happening when you set aspect ratio manually, does it start happening when you re-enable automatic aspect ratio detection (either via popup or key 'A')?
2. Does this issue persist if you restart the browser?
3. Does this issue persist if you reinstall extension?
4. What's your CPU (model + frequency) and do you have hardware acceleration enabled?

Thanks for your time.

**Comment by TangoFox4** [comment]
Hmm. I had it off now over the day and just reenabled it. No I can't reproduce it either.
The problem was gone when I disabled the plugin and came back after I reenabled it, so I'm sure it was causing it.
Maybe it depends on more. Maybe it has to do something with the video or something else?
I'll further investigate and tell you when I can reproduce it.

**Comment by TangoFox4** [comment]
Okay, it does it now again. On every Video. It seems to get worse over time. Been some hours now.
Makes me think there is some kind of memory bleeding? Is that possible?

1. Yes, still does it. It even get's worse to a point were it does not work at all, or the video stops after like 30 seconds. Also the plugin doesn't work now anymore (clicking left / center / right doesnt change the video). Loading a new video, that works again. Pausing still takes >10 seconds.

2. Re-enableing doesn't change anything.

3. No, when I restart the browser everything is fine again.

4. I did reinstall it the last time it still happened.

5. Intel 7700K @4.20GHz, 16GB RAM, GeForce 1070, PC is quite new, everything runs very smooth. It is enabled. I'm on Firefox Nightly.

Also noticed something weird: When I open the menu it **sometimes** says it cant detect a video on the page, but if it's just youtube:
https://i.imgur.com/8lBvTNz.png

**Comment by xternal7** [comment]
Ugh.

>It seems to get worse over time. Been some hours now.

Guess I'm doing a long term test tomorrow.

>Makes me think there is some kind of memory bleeding?

Hard to say it's a memory leak right off the bat, but given that the issue is fixed when the browser is restarted surely indicates it.

>https://i.imgur.com/8lBvTNz.png
Oh right. I'm not pulling the overpass font from anywhere either.

This issue happens because sometimes, the messages between different parts of extension get lost for some reason. Not sure if it's 100% fixable, but then again I don't exactly write firefox extensions for a living so I could be wrong.

So you basically have three scripts: content script (runs in every tab), background script (there's one instance per browser I think? bit more permanent), popup script.

Every time you switch a tab, background script asks the content script 'hey are there any videos? Please reply'. Content script replies, yes/no (content script also sends a command to background script if it detects video at a later time). If this reply gets lost, the background script will think there's no videos in current tab. But since messages, in general, always get delivered (even though replies may not), clicking the button should, in theory, still issue command.

When you open a popup, the popup script asks background script: "hey, does this page have any videos?" Background script relays the answer, so if reply from content script didn't come, it'll think there's no videos in this tab (command still works). Alternatively, the reply could also get lost (although this probably isn't the case here — keyboard shortcuts get placed under buttons using this process). 

(Un)fortunately I did manage to reproduce this bug where popup says 'no videos detected', and would you know. Video aspect does get changed if you press that button. For a split second, then it reverts back to default. This will be fun.

Hopefully I'll find this monologue helpful in the morning when try to figure what's wrong, I should be getting some sleep right now.

**Comment by TangoFox4** [comment]
I'm on MEZ / UTC+1, so I just woke up xD

Tell me if I can help you somehow debugging.

**Comment by TangoFox4** [comment]
Okay, I managed to reproduce it again by just watching videos on youtube for about 2 hours. I did nothing else on the PC.

When I started: https://i.imgur.com/ddq56t6.png
Now: https://i.imgur.com/xH4nD1Q.png

I don't know if that means something, but it went up a bit.

Instead of restarting the browser I tried to deactivate Ultrawidify, and the problem is instant gone.

I'm using only 3 Add-ons btw: NoScript, uBlock Origin and Ultrawidify.

**Comment by xternal7** [comment]
>Instead of restarting the browser I tried to deactivate Ultrawidify, and the problem is instant gone.

So the RAM usage falls the moment you deactivate Ultrawidify? Okay then, memory leak confirmed. Now to find it.

**Comment by TangoFox4** [comment]
No, the RAM usage stays about the same, it's just that the bug disappears when I deactivate Ultrawidify. I don't have to restart the browser. But I don't know if the RAM gets freed anyways just when you deactivate a add-on.

**Comment by xternal7** [comment]
So I've ran a youtube tab, put it on autoplay and yeah, can reproduce the issue when youtube plays videos continuously no interruptions for about 15 minutes. Let's see what `about:memory` has to say about stuff.

**Comment by xternal7** [comment]
So here's what I did and the results:

Opened youtube tab in a new window, kept it running. Closed tab when RAM usage got high-ish. Ran youtube videos for about 30-60 minutes while dicking around reddit or whatever, didn't really check. Closed the window afterwards and observed how much my system-wide RAM usage dropped.

**Extension enabled**
13.6 -> 8.6 GB 

**Extension enabled, youtube blacklisted**
Discovered that blacklisting code via extension button in the tab bar doesn't work. Hmm.


**Extension disabled via settings**
No increase/drop in RAM usage.

So yes, memory leak confirmed.

Btw fun fact, automatic aspect ratio detection is truly persistent after a few minutes.

**Comment by TangoFox4** [comment]
I'll have to restart the browser then more often xD

**Comment by xternal7** [comment]
You'll only need to close the youtube tab and wait a bit, in theory. All the extra RAM seems to get emptied the moment Firefox decides to throw away the data of the youtube tab.

(Assuming youtube is the only browser tab with videos in it)

**Comment by xternal7** [comment]
Hmm. There might be _no_ memory leak after all. The 13.6 -> 8.6 GB drop could have been due to me having console logging on and both consoles open. Needs more testing, though.

The delay between clicking on the video and video pausing _does_ seem to be related with RAM usage, though. When profiling RAM usage with devtools, RAM usage as captured by the console keeps steadily rising and then falling back down (probably something something garbage collection cycles). The greater the RAM usage at any given moment, the longer the delay. Because garbage collection is somewhat random and your clicking to stop the video is also random (from practical standpoint), you click at the time when RAM usage is random as well. Because RAM usage seems to correlate with the delay, the delay appears to be random as well. This theory seems likely considering that after you pause a video for a few seconds, RAM usage (as displayed by devtools) goes back down to roughly what it would be without the extension running (because autodetection runs once every 5-10 seconds while the video is paused) — and pausing happens immediately right after you resume the video.

That is, if my assumptions of how memory assignment and garbage collection work in javascript are correct.

**Comment by xternal7** [comment]
So here's a little update. I've been digging around on how to fix everything and more.

https://hacks.mozilla.org/2011/12/faster-canvas-pixel-manipulation-with-typed-arrays/
https://stackoverflow.com/questions/16679158/javascript-imagedata-typed-array-read-whole-pixel

So if I have less garbage references (but a bigger image), garbage collection will be faster (cos less references), execution using this approach will also be faster, therefore youtube will lag less — even though the RAM usage will be slightly bigger?

![screenshot_20180227_232138](https://user-images.githubusercontent.com/12505802/36758992-460c04ba-1c16-11e8-96e7-0c878ca50869.png)

So yeah, here's the results:

* not a memory leak
* it's apparently an issue with garbage collection
* Firefox has it worse than Chrome for some reason according to preliminary results, but I haven't tested this on a Firefox that's newer than FF56

Here's a code that takes this shit to ridiculous extremes as in screenshot above (the less you interact with the youtube tab, the worse it gets):

```
var fun = function(video,context){
    context.drawImage(video,0,0,1280,720);
    var image = new Uint32Array(context.getImageData(0,0,1280,720).data.buffer);    
    image = null;

    setTimeout(fun, 30, video, context)
}

var video = document.getElementsByTagName("video")[0];
var canvas = document.createElement("canvas");

canvas.width = 1280;
canvas.height = 720;

var context = canvas.getContext('2d');

fun(video, context);
```

I might be forced to drop the frequency of aspect ratio checks or get a little bit more creative with regards to RAM.

**Comment by TangoFox4** [comment]
Interesting. Can't you just catch the click on the video and stop the ratio checks then?

**Comment by xternal7** [comment]
It's not just clicks to the video. It's clicks to just about any thing on youtube that's affected in my tests.

Fortunately though, [someone over at reddit](https://www.reddit.com/r/iiiiiiitttttttttttt/comments/80qnss/i_tried_to_write_something_that_would/duyfg53/) (and if I'm not mistaken, one of my coworkers also suggested this in the same 24 hour period) came up with something that seems to help with RAM usage so far for some reason. 

Let's see if it still stays this way when I rewrite the rest of the function.

**Comment by TangoFox4** [comment]
Okay, I'll try it :)

**Comment by xternal7** [comment]
**Note:** commit says that this issue is fixed, and it kinda is. Here, on Github. The extension didn't get any updates yet and the code on Github is actually pretty  broken for some other reason (as I've discovered shortly after pushing the commit).

Don't try it just yet.

**Comment by TangoFox4** [comment]
I'll wait then..

**Comment by xternal7** [comment]
So apparently that bug is present on Chrome as well (_and_ is worse than Youtube), but it's impossible-ish to actually catch with browser tools because memory snapshots in Chrome ignore to-be-garbage-collected references. 

Video stuttering in Chrome seems to be caused by extension and Chrome apparently having per-tab limit on memory (?). The fuck.

**Comment by xternal7** [comment]
So I've found _another_ potential reason why RAM usage was outright exploding — because while the fix I've mentioned before certainly helped a lot, it didn't completely eliminate issues with ultra-excessive RAM usage. There was a second hole.

Under certain circumstances, the extension would try to relaunch aspect ratio autodetection, and it would keep relaunching it while the old instance of the script was still running. This is bad.

As I managed to work around the garbage collection issue, I would occasionally get RAM usage spikes out of nowhere. As I've played with autodetection parameters (size, polling period), RAM usage became sus af (=very suspicious): random spikes that came out of nowhere, increasing RAM orders of magnitude faster than it should. The only explanation for this phenomena was that script was running more often than it should.

So I started logging them executions of autodetection script. By default, I'd expect 30 executions per second. Console said that number could get up to 10 times as much, with current record holder being my Chrome beta tester who got to 1700+ executions. 

All of the sudden, the lagginess makes sense, and having script run 10 times in parallel would also explain high memory usage. On the other hand, it turns out that while shit garbage collection _was_ a legitimate issue (RAM usage seems to have improved since I've made adjustments for what I originally thought to be the problem), it wasn't the cause of this bug. It was just something I've noticed by accident.

Fixing this is going to be fun, because there's legitimate reasons for script to relaunch autodetection.

**Comment by xternal7** [comment]
**Finally done.**

So here's what was done: 

* Extension no longer lags youtube's click detection, regardless of RAM used.
* Improvements that were being implemented to autodetection increased RAM usage by _a lot_. Up to 400 MB if firefox was freshly started, up to (and sometimes over) 2 GB in case of Firefox running for a while or if the number of tabs was higher. (At 30 checks per second. This number drastically falls when you reduce the frequency, which is what I did)
* As a result, the resolution of the sample image was reduced
* Default rate at which I check for changes was also temporarily reduced from 30 per second to 1 per second, which reduces the amount of RAM used to the point where RAM usage is negligible. If your RAM rests mostly unused, you can safely increase the polling rate back to 30 using the extension popup, tab `Automatic aspect ratio detection (auto-ar) `. If you mess with the number, don't forget to hit 'Save'. 

Update should be up by the morning.
