### ISSUE TITLE
Blacklist doesnt work for parent directory

### ISSUE THREAD

**Issue by Etznab86** [xternal7/ultrawidify#30]
Ultrawidify breaks imgur gifs and gifs from similar sites. Blacklist was fixed but if I blacklist imgur.com ist doesnt block any child directory, like imgur.com/VghFgdnF e.g.
But this way surfign gifs is a chore. Any option to block whole parent directories?

**Comment by xternal7** [comment]
Are you using Chrome or Firefox?

Old issue: #26 (for reference)

**Comment by Etznab86** [comment]
Firefox 58.0.2 64bit
null

**Comment by xternal7** [comment]
Well that's strange, because it absolutely should.

You sure the extension got updated? I'm having trouble reproducing that.

>Any option to block whole parent directories?

It should block the entire domain, including subdirectories and subdomains by design.

**Comment by xternal7** [comment]
A proper fix should be up by the morning. I've also changed the default strategy - instead of ignoring blacklisted sites, the extension only works on sites that have been specifically enabled. By default, that's youtube and netflix. You can enable extension on additional sites by clicking the extension button, going to 'Settings for this site' tab and clicking 'allow'.
