### ISSUE TITLE
[Feature Request] Support for More Aspect Ratios

### ISSUE THREAD

**Issue by moriel5** [xternal7/ultrawidify#34]
I realize that this wasn't the point of the extension, however can support be added for other aspect ratios, such as 4:3 and 5:4?

**Comment by xternal7** [comment]
On manual correction side of things: maybe, I'll look into it in the next few months.

On automatic detection: eeeh. I'm not ruling it out completely, but don't count on it too much.

Until then, keyboard shortcuts `w` and `e` are the undocumented features that resize video so it's as wide or as tall as the screen. The parts of the video that don't fit

**Comment by moriel5** [comment]
Thanks, I wasn't holding my breath for anything beyond  basic support.

Although I take it that it's currently impossible to simply shrink the content, rather than crop it?

And I am sorry about adding to my request, however I had forgotten to ask about the x:10 variants of the currently supported resolutions (16:10, for example, is my preferred aspect ratio, due to it almost be as good for 16:9 for multimedia applications, while boosting my productivity due to it allowing me to see a bit more in terms of height).

**Comment by xternal7** [comment]
>Although I take it that it's currently impossible to [resize video without preserving aspect ratio]

Not at the moment. There is probably going to be one, eventually, when I get around to doing stuff. At the moment, though, priorities are (roughly in this order, which may change depending on my mood and/or bug reports): 

* Correct autodetection on Netflix (firefox only)
* Try to not kill myself when trying to convince Chrome to not screw up everything
* Improve Chrome a bit
* Reintroduce the settings page
* Reintroduce free-hand zoom and UI 
* site-specific CSS hacks (this extension can run on every site in theory ... in practice, some sites have css that doesn't follow some of the assumptions this extension makes. Examples: try enabling this extension on reddit, imgur or bitchute and see how video disappears)
* custom aspect ratios & stretch mode

>In that case, is there an extension that allowing for changing the aspect ratio without preserving the original aspect ratio?

Firefox? Dunno, my problem were the unnecessary letterboxing on 21:9 videos on youtube, because why upload 21:9 video when you can upload 16:9 with letterbox? (Mind: black bars only become ultra-annoying when they're all around the video). And a year and a half ago, I was the only one doing that on the Firefox side.

On Chrome, there's a few extensions that do stretching for one aspect ratio on one specific site, but there doesn't seem to be anything general purpose. I don't know any names off the top of my head, but I recall seeing an extension that stretches twitch broadcasts to 16:10. There's probably one for youtube as well.

**Comment by moriel5** [comment]
Thanks, and I am sorry for not checking the Chrome/Chromium side (although I do have Vivaldi and Chromium as secondary browsers (and Epiphany/GNOME Web, as a last resort)), as I had assumed this extension was Firefox-only.

As to we site support, I was only looking for for YouTube support.

In any case, keep it up.

**Comment by xternal7** [comment]
>Thanks, and I am sorry for not checking the Chrome/Chromium side

Ye no problem.

Anyway, I'll leave this thread open and update when I eventually get to stretching/other aspect ratios bit.

**Comment by xternal7** [comment]
As of v3.0.0, users can choose up to one (1) custom aspect ratio of their choosing via popup.
