### ISSUE TITLE
[Feature Request] Hulu support

### ISSUE THREAD

**Issue by OcDGamer98** [xternal7/ultrawidify#41]
Feature request is basically summed up in the title. Some movies and tv shows add black bars and some don't. It seems the way Hulu streams content doesn't actually get cropped depending on the aspect ratio. Added support for Hulu would be greatly appreciated (unless it already is).

**Comment by xternal7** [comment]
While this extension is by default enabled only for Netflix and Youtube, you can try enabling it on other sites as well. Click the extension button, go to `settings for this site` (topmost option). Under 'options for this site', select 'whitelist'.

![screenshot_20180805_103950](https://user-images.githubusercontent.com/12505802/43684197-e396a4f4-989b-11e8-873e-1be5e449cd40.png)

Try this.

# Caveats:

* I was recently made aware of an issue where settings may get lost with browser restart: #40 . I'm currently working on solving that issue.

* If that option doesn't do anything at all, it could mean whitelisting sites is also broken (possibly related to #40). If that turns to be the case (after I get some time to examine the problem more thoroughly).

Before I make any promises though, here's some caveats regarding autodetection:

## Autodetection quirks

Since Hulu (to my knowledge) uses DRM, autodetection feature will only work in Firefox — and even in Firefox, autodetection will have some limitations.

Changing aspect ratio manually should work in every browser as soon as hulu support is added, though.

**Comment by OcDGamer98** [comment]
Thanks for the help. I messed around with the settings a little bit, and somehow ended up getting it working. I just ended up whitelisting the site and settings it to always enable the extension on the site. I was not aware it was this easy to enable it on Hulu, thank you!

**Comment by xternal7** [comment]
No problem. 

By the way — just another reminder — there's a bit of an issue I'm currently having with saving extension settings. (bug #40 and I've reproduced it) If extension forgets any of those settings you messed around with, feel free to bring that up.

**Comment by xternal7** [comment]
As of v4.0.0, autodetection is 'on' by default on all sites.
