### ISSUE TITLE
Control UI on Youtube is not displayed correctly

### ISSUE THREAD

**Issue by heubergen** [xternal7/ultrawidify#5]
Since some days the youtube control ui is not shown correctly:
![youtube-controll](https://cloud.githubusercontent.com/assets/5529410/25098608/8147c03e-23a9-11e7-8b5a-b5de76d96810.png)

When I deactivate ultrawidify, it seems to work again so I think it's some new issue with the extensions.

My Browser Setep:
FF Nightyl 55 x64 with Win10 (Creators Update Fast Ring)
My extensions:
- 1Password
- Advanced History
- Decentraleyes
- Min Vid
- No Google Link Rewrite (WebExtension)
- Overlay Scrollbars
- Pulse
- Test Pilot
- uBlock Origin/webext
- Ultrawidify

**Comment by xternal7** [comment]
There hasn't been any updates (to Firefox or Chrome version, as github version currently doesn't work on Netflix due to a major rewrite) since end of January. Strange that this issue has appeared recently.

I have some extra questions:

1. Does this happen when you're watching video on youtube, when the video you're watching is embedded on some other site (think watching stuff on /r/videos on reddit), or both?
2. Does the problem still happen if you disable Min Vid instead?
3. Does this problem go away if you resize the browser window?



And finally, because Netflix is the reason there was no update in the past couple of months:

4. Do you use netflix? 

If you don't use netflix at all, I can build you a temporary version using what I have at the moment (it could take a day or two, or three (depending on how things go IRL) since I would have to fix some things first).

Pros: 
 * UI might work properly
 * If it doesn't, you could hide UI altogether (If I'm not mistaken, [you even opened the feature request for it](https://github.com/xternal7/ultrawidify/issues/1), so I figure you'd actually prefer this solution)

Cons:
 * No netflix
 * No automatic updates (but I could tell you once the updates make it to a stable version).

**Comment by heubergen** [comment]
Hi @xternal7 
Sorry for bothering you, a new profile solved the issue so I really think that it was just a mess.

Best
heubergen

**Comment by xternal7** [comment]
Ah, no problem.

**Comment by heubergen** [comment]
Hi

After some days the issue is here again so I'm not sure if it was really a profile related issue.
To you questions:
I'm watching the videos directly on youtube.com and I removed Min Vid in the meantime. Resizing the window don't help and no I don't use Netflix (at least not with this browser).

May you can send me the new build and I'll let you know if it helps?

**Comment by xternal7** [comment]
Hi,

I've had a busy weekend so I couldn't get on it right away, and then I kinda forgot for a while. Sorry about that. Here's the new build:

http://tamius.net/ultrawidify/versions-git/ultrawidify-git_1.3a1.xpi

This should work on youtube. Tell me if the UI is still broken for you. You can also test the "hide UI" feature.

*KNOWN QUIRKS:*
* You must visit a youtube video before opening the settings page. (Reason being that settings page doesn't initialize default values if they are undefined, which may lead to things not working the way they should)
* When you open the 'settings' page, the "Show UI in the player bar" option is unchecked even though it's enabled. If you want to disable the UI, you need to check it, and then uncheck it again.
* Don't touch the 'Site options' tab on the settings page, as that functionality is unfinished and doesn't work yet.
* obviously Netflix still doesn't work (I know you said you don't use netflix, just putting that out for any third party who might see the shiny blue link and not read the rest of our interaction)
* You won't be getting any automatic updates for this version, so I'll inform you when I eventually manage to get all the changes on the AMO version. I'll also leave this issue open until then.
* that's about all I can think about right now

**Comment by heubergen** [comment]
Hi there, no problem I'm patience thank you for your time and work.

I run into an issue.
Steps:
* Visit youtube.com
* Open ultrawidify settings
* Set Shortcuts for force 21:9 or Fit to width to CTRL + ALT + D

When I now try to use the Shortcut on youtube it doens't seem to work.
I'm also unable to see the UI at all.

My Browser: Nightly 55 x64 Win10

**Comment by xternal7** [comment]
... I actually have no idea what's going wrong here. (I'll admit I haven't tested that version on Nighlty)

>I'm also unable to see the UI at all.

If you haven't disabled the UI, that usually means that extension either failed to start or crashed before UI got up. Debugging also doesn't print a thing in Nightly, which means that the extension doesn't get started. At all. Not even the first few messages that should display before any code that could cause extension to fail runs. 

Not seeing anything in console has so far only happened when the syntax was wrong. Since this works in normal (and beta) Firefox, the syntax must be correct (also this javascript validator I sometimes run the code against said so) - and that leaves me with little room for ideas. I've found some unrelated things that are wrong, but that shouldn't be the reason it works in normal FF, but not in Nightly.

*Note to self:* remove browser-detection code from src/uw.js, it could screw things later down the line.

**Comment by heubergen** [comment]
So you can reproduce the error if I understood you correctly?
A lot of things happens between FF Beta and FF Nightly right know with Project Photon, the WebExtension API etc. so there is a really good probability for some breaking changes. If you have the time you can join [this](https://irc.mozilla.org/webextensions) IRC channel from Mozilla and ask them if they could help you out a little bit. Just need to change https:// through irc:// for the link

**Comment by gr1mz** [comment]
Hello,

I'm having the exact same problem with the latest nightly x64.
repro with "Enhancer for youtube" and ultrawidify.
I have to choose one or the other. (i recall them both together working fine in the regular version)
https://www.mrfdev.com/enhancer-for-youtube

Ultrawidify on its own works fine, and enhancer on its own work fine as well.
I don't know what could cause this, but i can't back down to the regular firefox version until the youtube  playback stutter is gone.

**Comment by xternal7** [comment]
@heubergen @gr1mz 

I've had to take some time off from developing this extension due to some real life stuff (exams, arm injury, still have to finish my diploma by the end of september), sorry for the lack of updates. If all goes well and according to plan, I'll continue working on this extension in October.

In the mean time, I'd like to know if you still experience the same issues. 

If I'm not mistaken, what was "latest Nightly" in April/May has became stable since then, and my extension worked for me on stable throughout the entire time.

**Comment by heubergen** [comment]
I changed my setup since then so I'm longer using this extension, sorry.

**Comment by xternal7** [comment]
No problem. Thanks for the reply.
