### ISSUE TITLE
Can't unblacklist Netflix

### ISSUE THREAD

**Issue by RafaWanner** [xternal7/ultrawidify#55]
**Describe the bug**
I try to whitelist / defaut automatic detection on netflix but it just lags and when i close it and open again it goes back to blacklist

**To Reproduce**
tried to watch a netflix movie

**Expected behavior**
it should stay in whitelist and automatic detect when the movie is in 21:9

**Screenshots**
Opening
![image](https://user-images.githubusercontent.com/46364808/50673979-72c70700-0fc9-11e9-8f88-8a7704411324.png)
Changing to whitelist
![image](https://user-images.githubusercontent.com/46364808/50673986-85d9d700-0fc9-11e9-801e-7ea026936daa.png)
Opening again
![image](https://user-images.githubusercontent.com/46364808/50673991-90946c00-0fc9-11e9-9b75-896ec925b0e6.png)
Changing to Default
![image](https://user-images.githubusercontent.com/46364808/50674036-ca657280-0fc9-11e9-8346-bf424b724f48.png)
Opening again
![image](https://user-images.githubusercontent.com/46364808/50674039-d9e4bb80-0fc9-11e9-9f6f-82f9ec79b119.png)

**Browser and OS**
 * Browser/browser version: Chrome
 * Operating system: Windows 10 Pro
 * Ultrawidify version: 3.2.2

**Additional info**
it works just fine in youtube 
on netflix i can't manualy set to 21:9 either, actually can't change the screen at all
i never marked to blacklist netflix
i used to use better netflix that could also use the 21:9 feature but for some reason netflix wouldn't iniciate any video anymore so i unistalled it and installed Ultrawidefy
i used Ultrawidefy yesterday and despite it didn't cropped automatically it did worked with manual crop and i didn't saw if it was blacklisted

**Comment by xternal7** [comment]
I was thinking about writing a reply back when this happened, decided against because you closed the issue yourself (presumably because after all, it does say in the readme that autodetection doesn't and can't work on Netflix in Chrome). So I saw no need to reiterate the "autodetection doesn't work on Netflix" line. 


I'm mostly here because of this:

>but it just lags and when i close it and open again it goes back to blacklist

**Technical details:** In order to detect aspect ratio, extension needs to ask the browser to get the pixels from the video. Some sites (e.g. Netflix, but it's not the only one) use DRM that prevents the browser from getting said pixels from video. When the website tells the browser "no, you can't get those pixels", the browser can react in two ways. 

There's the Firefox way, where browser will raise hell and crash the script if you don't handle that. This is the preferable way, because if you account for the possibility of various hissy fits, you can handle them. The site doesn't want to share video pixels? No problem, Firefox allows extensions to screenshot the webpage. And if screenshot doesn't work, you get another error that tells you to knock it off.

And then there's the Chrome way, where the browser will just give you a black square. This is a problem, because the wider the black edge, the more time the extension needs to determine the aspect ratio. ~~Although I need to check whether the black square Chrome gives me is black rather than transparent~~

This comment is mostly here for anyone who stumbles over this issue.
