### ISSUE TITLE
Used up all my ram

### ISSUE THREAD

**Issue by Cheesmeet** [xternal7/ultrawidify#57]
Tried to install it and was excited to try it out. But then my firefox stopped working properly, clicking on another tab would take 30-60 seconds, and when I checked my task manager It was using 18gb of ram! My Firefox uses 2gb of ram without it. When I restarted firefox it was automatically disabled. However, I do have a lot of tabs open. 89 tabs to be exact. (Yes I counted. :b) I thought maybe it has something to do with it checking every tab, but I'm not sure since it wasn't me who programmed it. I do have 32gb of 3200hrtz memory, and my ram usage wasn't 100% so I'm not sure why Firefox wouldn't respond though.

**Comment by xternal7** [comment]
>Tried to install it and was excited to try it out.

I presume this was a clean, 100% fresh install then. Still, what's your version?

Anyway, I've had someone had a somewhat similar issue recently on reddit, except they were a long-time user and the issue started happening like ... recently, even though the last update happened in September 2018. The issue was fixed by uninstalling the extension, installing an older version and then upgrading from an older version.

**Few questions before I say anything definite.**

* **How long did you watch youtube/netflix before RAM went from 0 to 18 GB?**
* **How many of those tabs are netflix/youtube?**
* **What happens if you only have one youtube tab opened? How fast does RAM usage increase then?**
(Note — you don't need to close all tabs to do the last bullet item. Close the browser (or crash it with taskmanager), open it (restore session), open a single youtube tab and don't touch the others. Other tabs should remain unloaded if you do so)

I use similar overkill number of tabs and haven't got issues to that extent. Assuming you don't visit all the tabs at once, having great number of tabs open shouldn't be an issue becasue Firefox won't load them until you visit them for the first time after launching the browser.

>I thought maybe it has something to do with it checking every tab

Sorta but no. 

There was an issue with RAM usage that was fixed about a year ago.

The main RAM hog ***used to*** be autodetection running at 30 fps. Autodetection renders a 640x360-ish image, at 4 bytes per pixel that nets about ~1 MB per frame. Because javascript garbage collection is trash, those 1 MB frames wouldn't get thrown out of memory as soon as they should, those frames quickly started piling up, giving you a nice and steady RAM usage increase of about +30MB/s (or ~1.8 GB/min) per video per tab (tabs without videos don't contribute to that).

That was fixed last march/april, though. Since then, autodetection runs at 1.3 fps when video is playing (about +75 MB per minute. This is manageable increase because by the time extension uses a noticeable amount of RAM, garbage collection tends to come around and keep RAM usage at reasonable levels). If the video is playing or has ended, autodetection runs even slower (at about 0.1 fps IIRC, so RAM usage is negligible).

Checking every tab might be an issue, but I don't know whether pausing autodetection in inactive tabs on tab switch is currently enabled or not. Don't remember because I've been working on ensuring other functionalities work for the past few months, so that's the sorta part of the issue.

My money is — for the time being, at least — on settings somehow getting corrupted and causing autodetection to run more often than expected.

> and my ram usage wasn't 100% so I'm not sure why Firefox wouldn't respond though.

What's the CPU usage, and does Firefox have any process that eats up 100% of a single core of your CPU?
