### ISSUE TITLE
Settings not being saved

### ISSUE THREAD

**Issue by yusareba** [xternal7/ultrawidify#59]
**Describe the bug**
Settings are not being saved for future page loads. I have only tested this using Youtube. However the result is the same for all chromium based browsers. Chrome, Vivaldi, etc

**To Reproduce**
On Extension and Site Settings areas: "Automatic Detection" and "Default Stretching Mode" select any non-default choices. navigate to another video on the website (Youtube) for example and settings will have not saved and changed.

**Expected behavior**
I would expect that by changing Extension and Site settings, that they would save for the next time those pages are loaded.

**Screenshots**
When it does work, it works great! 

**Browser and OS**
 * Browser/browser version: Chrome Version 72.0.3626.119 (Official Build) (64-bit)
 * Operating system: Windows 10 Pro
 * Ultrawidify version: 3.2.2

**Additional info**
Everything else is great

**Comment by xternal7** [comment]
So yeh, good news: I'm pretty sure I've fixed that this past weekend.

Bad news: unfortunately it's going to take a while longer before extension is ready to be released, so I'll be leaving that open for the time being. There's been some pretty big changes under the hood, which is why that thing is taking me way longer than expected.

**Comment by yusareba** [comment]
No worries. It's no big deal to change settings per video. I'm grateful in any case, but figured you should know if you didn't already. 

Thank you

**Comment by xternal7** [comment]
Oi right, this should work now.
