### ISSUE TITLE
[Feature Request] Align videos in fullscreen to the left (or right)

### ISSUE THREAD

**Issue by TangoFox4** [xternal7/ultrawidify#6]
Hi, awesome plugin!
I have a feature request that would fit it 😁 

If you use youtube in fullscreen on 21:9 screens, 16:9 content will cause black borders on the left and the right. I hate that the video gets centered then, I would love to have it on the left, so I have some space on the right to do other things.
Using youtube windowed is not really nice either, it never uses a good size.

So I would like to request a button that changes the alignment of the video in fullscreen.

**Comment by xternal7** [comment]
Thanks for the suggestion. I'll probably implement it once I get back to working on this extension, but that will take time because:

* a rewrite that would ease adding support for other sites is still not finished
* an injury has put me out of commission for a while
* I'll need to double-up my efforts on my diploma and other IRL stuff when my injury heals

In the mean time: I hope that you're aware that youtube — while playing full screen — cannot be covered with other windows, **unless** you force a window to always stay on top. On linux, that's easy. Windows would require third party software. But I suppose you know that already.

If you're on firefox, you might want to check out this extension: [Tile Tabs](https://addons.mozilla.org/en-US/firefox/addon/tile-tabs/) — you can use this extension to vertically tile multiple tabs. Since this extension works in full screen as well, you can kinda (ab)use it to get the functionality you seek until I return from this unexpected involuntary hiatus I'm having right now.

Note that Tile Tabs will stop working once Firefox abandons its old extension system in favour of webextensions in the near future. WebExtension version of Tile Tabs is utter crap (not developer's fault though) and doesn't work on fullscreen windows (f11 kind of fullscreen), because there's certain things that old extension API could do that WebExtension API can't.

**Comment by TangoFox4** [comment]
Thanky for the reply :)

I play League of Legends, and the champ select is always a forced on top window. It's the most played game of the world, so I think a lot of people have that problem :D

Tile Tabs doesn't really do what I want. The problem is not the brower, it is youtube itself. Without fullscreen the video size won't get that big and I want to use the full screen.

Anyway. Get well soon!

**Comment by xternal7** [comment]
But Tile Tabs does kinda do what you're asking (or at least if I understand things right) — you can trick video to one side of the screen by tiling a dummy tab to the left or right: http://imgur.com/a/vvHTu

This is actually how I demo/test this extension on my laptop, where I need to simulate 21:9 monitor on 16:9.


**... (unless you're using Chrome or Firefox >=57, in which Tile Tabs works fundamentally differently.** But FF57 shouldn't be out yet, at least not in stable)

**Comment by TangoFox4** [comment]
Ah I see, I didn't test fullscreen while having it on. You're right, that kinda does what I want.
It is a little anoying to use but it will do the trick for now. I changed browser.display.background_color to #000000 to get the right side black.

Thanks!

**Comment by TangoFox4** [comment]
Haha, my hero :D
It has this feature now, works great! So the issue can be closed.
Thanks and a happy new year :)
