### ISSUE TITLE
Cropping mode resets when next video loads (on Netflix at least)

### ISSUE THREAD

**Issue by vkapartzianis** [xternal7/ultrawidify#69]
**Describe the bug**
Cropping mode doesn't seem to stick when the next video loads, on Netflix at least. I'm not sure if this is a bug or a "missing feature".

**To Reproduce**
Set the cropping mode to 18:9 for an episode in Dark season 2 or Stranger Things season 3 on Netflix (and on an ultrawide monitor). Skip to the end of the episode and wait until the next episode loads. The cropping mode is reset (black bars appear at the top and bottom of the video).

**Expected behavior**
I would expect the cropping mode to be 18:9 for subsequent episodes, until I reset it.

**Browser and OS**
 * Browser/browser version: Microsoft Edge (Chromium-based) / 77.0.197.1 dev (64-bit)
 * Operating system: Windows 10 1903 (10.0.18362.207)
 * Ultrawidify version: 4.1.2

**Additional info**
Same things happens with Chrome 75.0.3770.100

**Comment by xternal7** [comment]
Not really a bug, this is by design as this kind of behaviour is generally preferred on youtube where aspect ratios vary more. It's also in a huge blindspot thanks to autodetection and the by fact that Netflix has been giving most (but not all) non-16:9 movies a proper crop in my region by default.

You got a point though, sometimes semi-permanent crop settings would make sense.

**Comment by xternal7** [comment]
Implemented with 4.4.0.

It will probably take a while before the update actually makes it to Chrome Web Store, because extension permissions triggered a manual review.
