### ISSUE TITLE
Shortcuts doesn't work on Russian keyboard layout

### ISSUE THREAD

**Issue by LiprikON2** [xternal7/ultrawidify#70]
Cropping mode shortcuts doesn't work with keyboard layout set to Russian, but work normally with English layout

 * Browser/browser version: Chrome 75.0.3770.142 (Official Build) (64-bit)
 * Operating system: Windows 10 Pro 1903
 * Ultrawidify version: 4.2.2

**Comment by xternal7** [comment]
Just a side note: you can probably edit keyboard shortcuts (or add new ones and hide them from the extension menu) to accept cyrillic characters in the settings. That's merely a workaround, though, and slightly less than ideal.

**Notes to self** when I get some time to review this:

* https://stackoverflow.com/questions/1772179/get-character-value-from-keycode-in-javascript-then-trim

**Comment by xternal7** [comment]
Good news, this is sorta fixed. Sorry it took this long, there was a few worse issues + life sometimes gets in a way, big time.

This is hopefully gonna get released by the end of the week at earliest, after the holidays (2019-11-04) at latest (and then however long the Firefox/Chrome stores will take to distribute the update on top of that). 

**Important notes:**
This isn't going to get magically patched for existing users. It will require you to reset settings in extension settings because I've got no way of patching that.

**Another side note:**
Zoom key (`z` by default) will actually be bound to letter 'Y' on QWERTY layout. Two reasons for this decision: 1. I'm using QWERTZ layout, so 'Z' key is where QWERTY users will find the 'Y' key; 2. 'unzoom' is on letter 'U' so I figure this makes at least some amount of sense.

Feel free to share any opinions about this decision. Alternative option is to duplicate 'zoom' shortcut so it triggers both on 'Y' and 'Z' so things are consistent between layouts.

**Comment by xternal7** [comment]
Status update for Chrome web store — Chrome distribution is going to take a while longer than usual, since the permissions extension needs now trigger a manual review by google.

Which might end in a rejection because I'm doing some things that some may consider bad coding practices (namely — [I give zero fuck about the fact that Google Chrome does not support `tabs.removeCss()`](https://stuff.tamius.net/sacred-texts/2019/08/24/ultrawidify-the-twitchy-twitch-problem/).

Yikes.
