### ISSUE TITLE
32:9

### ISSUE THREAD

**Issue by flakdeezy** [xternal7/ultrawidify#79]
Can we get a 32:9 update for ultra wide monitors

**Comment by xternal7** [comment]
* Automatic aspect ratio detection pretty much takes whatever you give it (unless it's a pillarboxed video, but I haven't been able to find one of these yet _ever_)
* there's pretty much no 32:9 content out there, so the option is irrelevant
* manual aspect ratios can be added by user in extension settings (UX is a bit lacking, but it's an option. Custom aspect ratios have been a thing since forever)

Depending on whether you want to over-crop or stretch: 
* When everything else fails, there's always 'fit to width' option left and manual zoom. Since there's very little 32:9 content out there, 'fit to width' would overcrop about as much as native 32:9 option
* If over-crop is not okay, 'hybrid stretch' has been a thing for a while now.

So yeah, as far as I'm concerned, that's already implemented.
