### ISSUE TITLE
FR: Manual squashing of incorrect 16:9 vids to 4:3

### ISSUE THREAD

**Issue by JohnVeness** [xternal7/ultrawidify#81]
I realise what I'm about to describe isn't the main focus of this addon, but you certainly understand the importance of aspect ratios and I haven't found another addon that will fix this:

There are many videos on YouTube of old TV programs which should be in 4:3, but which the uploader has stretched to 16:9, whether intentionally or ignorantly. There is nothing in the native YouTube interface to squash them horizontally back to 4:3.

It would be great if there was an option in ultrawidify to do this. It couldn't be autodetected, so would have to be a manual toggle, which is fine with me.

Alternatively, if anyone knows of another addon that allows this manipulation, please let me know.

**Comment by xternal7** [comment]
You can actually already do that... sorta (by abusing features that weren't intended to do these things) I'm gonna apologize for burning through your data plan if you're reading this thread on mobile, but screencap+paste is much more convenient than exporting stuff to jpg first so ...

Add 4:3 option (go to extension settings -> actions & shortcuts -> click 'add new option')

![slika](https://user-images.githubusercontent.com/12505802/69574283-0fbad600-0fc8-11ea-9ef9-0937838d8117.png)

Click your way through menu:

![slika](https://user-images.githubusercontent.com/12505802/69574387-42fd6500-0fc8-11ea-92be-84c3a479db6a.png)

**Make sure to specify aspect ratio as a single number** (e.g. putting 4:3 or 1:1.25 isn't gonna work, you must enter 1.25). **Aspect ratio you need to enter depends on your monitor aspect ratio - see 'caveats' section below.**

Make sure to tick 'show in popup' if you wanna see it in popup, as well. Shortcuts are optional.

![slika](https://user-images.githubusercontent.com/12505802/69574465-835ce300-0fc8-11ea-923c-72bac39e4c45.png)

When you're watching a video, click the 4:3 crop option you've just added, then click 'hybrid stretch'.

Actually, you don't even have to do that. You can just click the orange plus once more and add the hybrid stretch action:

![slika](https://user-images.githubusercontent.com/12505802/69575083-df743700-0fc9-11ea-842c-be3172094a5b.png)

Click save, and it's gonna pop up in the extension menu. Down there at the bottom:

![slika](https://user-images.githubusercontent.com/12505802/69575261-29f5b380-0fca-11ea-8ab4-ea6482ced0c5.png)

Congrats, you're winning (but if you changed keyboard shotcuts with youtube opened, you might want to do a refresh): 

![slika](https://user-images.githubusercontent.com/12505802/69574748-31688d00-0fc9-11ea-8827-fa01da56a1b7.png)

There's no black background in normal view because reasons, but here we go.

Admittedly, the menu is not the most user friendly thing that exists, but it's niche enough I don't have to care (and when I do, I can just point and say RTFM ... except [TFM](https://github.com/xternal7/ultrawidify/wiki/Defining-custom-actions-and-changing-keyboard-shortcuts) is a mess, too, so I can't really.

# IMPORTANT CAVEATS

## Stretching is separate from crop

If the image is stretched (or squished) and you press 'reset (crop)', the image will remain stretched or squished. Setting crop has no effect on whether image gets stretched or not (with one tiny exception) and vice versa (except if you use 'basic stretch' - basic stretch mode ignores cropping). 

## When in full screen mode, squishing may require something different

Turns out that the amount of squish you get is dependent on how wide the player area is. So the "crop ratio" in the shortcut you made should really be "squish ratio." You get that by dividing aspect ratio of your monitor with 4:3. 

4:3 is basically 12:9, which gives us the following numbers (in case you watch in full screen):

* **16:9 monitors** -> 16:9 / 12:9 = 16*~~9~~  / 12*~~9~~ =  16 / 12 = **1.25**
* **21:9 monitors** -> 21:9 / 12:9 = 21 / 12 = **1.75**
* **32:9 monitors** -> 32:9 / 12:9 = 32 / 12 = **2.5**

So if you enter the 'correct' number for the aspect ratio of your monitor, all is going to be fine:

![slika](https://user-images.githubusercontent.com/12505802/69577939-bc4c8600-0fcf-11ea-92e8-49796db0534a.png)

If you're going to blindly enter `1.25`, you're going to have a bad time in theater mode and fullscreen:

![slika](https://user-images.githubusercontent.com/12505802/69575487-a4263800-0fca-11ea-8a7c-0dd531298708.png)

![slika](https://user-images.githubusercontent.com/12505802/69575636-f10a0e80-0fca-11ea-842b-cab4bc3fc503.png)

# Conclusion thingy

Obviously, this is more contrived than I'd like, so proper "squish to" options will probably come eventually.

**Comment by xternal7** [comment]
As of 4.4.2, this feature is included in the extension, proper. 

Feedback welcome.

Update is live on AMO/Firefox (it'll be updated when Firefox pulls the update).
On Chrome, the update will probably land early next week as my extension is subject to review (because 'all sites' permission).

**Comment by JohnVeness** [comment]
This seems to work great on a few videos I've tried. Many thanks for implementing this so quickly :)
